# Generated by Django 5.1.2 on 2024-10-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_employee_delete_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "mssv",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("class_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
